/* Adobe Corporate Use values of Adobe Glyph List names, mapped to the
 * character each is a variant of. Sorted by value for binary search.
 * Generated by emit_adobe_private_use.py. Do not edit. */

static const struct { unsigned short pua, ucs; } fz_adobe_private_use[] =
{
	{ 0xf6be, 0x0237 }, /* dotlessj -> LATIN SMALL LETTER DOTLESS J */
	{ 0xf6c9, 0x00b4 }, /* Acute -> ACUTE ACCENT */
	{ 0xf6ca, 0x02c7 }, /* Caron -> CARON */
	{ 0xf6cb, 0x00a8 }, /* Dieresis -> DIAERESIS */
	{ 0xf6ce, 0x0060 }, /* Grave -> GRAVE ACCENT */
	{ 0xf6cf, 0x02dd }, /* Hungarumlaut -> DOUBLE ACUTE ACCENT */
	{ 0xf6d0, 0x00af }, /* Macron -> MACRON */
	{ 0xf6d9, 0x00a9 }, /* copyrightserif -> COPYRIGHT SIGN */
	{ 0xf6da, 0x00ae }, /* registerserif -> REGISTERED SIGN */
	{ 0xf6db, 0x2122 }, /* trademarkserif -> TRADE MARK SIGN */
	{ 0xf6dc, 0x0031 }, /* onefitted -> DIGIT ONE */
	{ 0xf6df, 0x00a2 }, /* centinferior -> CENT SIGN */
	{ 0xf6e0, 0x00a2 }, /* centsuperior -> CENT SIGN */
	{ 0xf6e1, 0x002c }, /* commainferior -> COMMA */
	{ 0xf6e2, 0x002c }, /* commasuperior -> COMMA */
	{ 0xf6e3, 0x0024 }, /* dollarinferior -> DOLLAR SIGN */
	{ 0xf6e4, 0x0024 }, /* dollarsuperior -> DOLLAR SIGN */
	{ 0xf6e5, 0x002d }, /* hypheninferior -> HYPHEN-MINUS */
	{ 0xf6e6, 0x002d }, /* hyphensuperior -> HYPHEN-MINUS */
	{ 0xf6e7, 0x002e }, /* periodinferior -> FULL STOP */
	{ 0xf6e8, 0x002e }, /* periodsuperior -> FULL STOP */
	{ 0xf6e9, 0x0061 }, /* asuperior -> LATIN SMALL LETTER A */
	{ 0xf6ea, 0x0062 }, /* bsuperior -> LATIN SMALL LETTER B */
	{ 0xf6eb, 0x0064 }, /* dsuperior -> LATIN SMALL LETTER D */
	{ 0xf6ec, 0x0065 }, /* esuperior -> LATIN SMALL LETTER E */
	{ 0xf6ed, 0x0069 }, /* isuperior -> LATIN SMALL LETTER I */
	{ 0xf6ee, 0x006c }, /* lsuperior -> LATIN SMALL LETTER L */
	{ 0xf6ef, 0x006d }, /* msuperior -> LATIN SMALL LETTER M */
	{ 0xf6f0, 0x006f }, /* osuperior -> LATIN SMALL LETTER O */
	{ 0xf6f1, 0x0072 }, /* rsuperior -> LATIN SMALL LETTER R */
	{ 0xf6f2, 0x0073 }, /* ssuperior -> LATIN SMALL LETTER S */
	{ 0xf6f3, 0x0074 }, /* tsuperior -> LATIN SMALL LETTER T */
	{ 0xf6f4, 0x02d8 }, /* Brevesmall -> BREVE */
	{ 0xf6f5, 0x02c7 }, /* Caronsmall -> CARON */
	{ 0xf6f6, 0x02c6 }, /* Circumflexsmall -> MODIFIER LETTER CIRCUMFLEX ACCENT */
	{ 0xf6f7, 0x02d9 }, /* Dotaccentsmall -> DOT ABOVE */
	{ 0xf6f8, 0x02dd }, /* Hungarumlautsmall -> DOUBLE ACUTE ACCENT */
	{ 0xf6f9, 0x0142 }, /* Lslashsmall -> LATIN SMALL LETTER L WITH STROKE */
	{ 0xf6fa, 0x0153 }, /* OEsmall -> LATIN SMALL LIGATURE OE */
	{ 0xf6fb, 0x02db }, /* Ogoneksmall -> OGONEK */
	{ 0xf6fc, 0x02da }, /* Ringsmall -> RING ABOVE */
	{ 0xf6fd, 0x0161 }, /* Scaronsmall -> LATIN SMALL LETTER S WITH CARON */
	{ 0xf6fe, 0x02dc }, /* Tildesmall -> SMALL TILDE */
	{ 0xf6ff, 0x017e }, /* Zcaronsmall -> LATIN SMALL LETTER Z WITH CARON */
	{ 0xf721, 0x0021 }, /* exclamsmall -> EXCLAMATION MARK */
	{ 0xf724, 0x0024 }, /* dollaroldstyle -> DOLLAR SIGN */
	{ 0xf726, 0x0026 }, /* ampersandsmall -> AMPERSAND */
	{ 0xf730, 0x0030 }, /* zerooldstyle -> DIGIT ZERO */
	{ 0xf731, 0x0031 }, /* oneoldstyle -> DIGIT ONE */
	{ 0xf732, 0x0032 }, /* twooldstyle -> DIGIT TWO */
	{ 0xf733, 0x0033 }, /* threeoldstyle -> DIGIT THREE */
	{ 0xf734, 0x0034 }, /* fouroldstyle -> DIGIT FOUR */
	{ 0xf735, 0x0035 }, /* fiveoldstyle -> DIGIT FIVE */
	{ 0xf736, 0x0036 }, /* sixoldstyle -> DIGIT SIX */
	{ 0xf737, 0x0037 }, /* sevenoldstyle -> DIGIT SEVEN */
	{ 0xf738, 0x0038 }, /* eightoldstyle -> DIGIT EIGHT */
	{ 0xf739, 0x0039 }, /* nineoldstyle -> DIGIT NINE */
	{ 0xf73f, 0x003f }, /* questionsmall -> QUESTION MARK */
	{ 0xf760, 0x0060 }, /* Gravesmall -> GRAVE ACCENT */
	{ 0xf761, 0x0061 }, /* Asmall -> LATIN SMALL LETTER A */
	{ 0xf762, 0x0062 }, /* Bsmall -> LATIN SMALL LETTER B */
	{ 0xf763, 0x0063 }, /* Csmall -> LATIN SMALL LETTER C */
	{ 0xf764, 0x0064 }, /* Dsmall -> LATIN SMALL LETTER D */
	{ 0xf765, 0x0065 }, /* Esmall -> LATIN SMALL LETTER E */
	{ 0xf766, 0x0066 }, /* Fsmall -> LATIN SMALL LETTER F */
	{ 0xf767, 0x0067 }, /* Gsmall -> LATIN SMALL LETTER G */
	{ 0xf768, 0x0068 }, /* Hsmall -> LATIN SMALL LETTER H */
	{ 0xf769, 0x0069 }, /* Ismall -> LATIN SMALL LETTER I */
	{ 0xf76a, 0x006a }, /* Jsmall -> LATIN SMALL LETTER J */
	{ 0xf76b, 0x006b }, /* Ksmall -> LATIN SMALL LETTER K */
	{ 0xf76c, 0x006c }, /* Lsmall -> LATIN SMALL LETTER L */
	{ 0xf76d, 0x006d }, /* Msmall -> LATIN SMALL LETTER M */
	{ 0xf76e, 0x006e }, /* Nsmall -> LATIN SMALL LETTER N */
	{ 0xf76f, 0x006f }, /* Osmall -> LATIN SMALL LETTER O */
	{ 0xf770, 0x0070 }, /* Psmall -> LATIN SMALL LETTER P */
	{ 0xf771, 0x0071 }, /* Qsmall -> LATIN SMALL LETTER Q */
	{ 0xf772, 0x0072 }, /* Rsmall -> LATIN SMALL LETTER R */
	{ 0xf773, 0x0073 }, /* Ssmall -> LATIN SMALL LETTER S */
	{ 0xf774, 0x0074 }, /* Tsmall -> LATIN SMALL LETTER T */
	{ 0xf775, 0x0075 }, /* Usmall -> LATIN SMALL LETTER U */
	{ 0xf776, 0x0076 }, /* Vsmall -> LATIN SMALL LETTER V */
	{ 0xf777, 0x0077 }, /* Wsmall -> LATIN SMALL LETTER W */
	{ 0xf778, 0x0078 }, /* Xsmall -> LATIN SMALL LETTER X */
	{ 0xf779, 0x0079 }, /* Ysmall -> LATIN SMALL LETTER Y */
	{ 0xf77a, 0x007a }, /* Zsmall -> LATIN SMALL LETTER Z */
	{ 0xf7a1, 0x00a1 }, /* exclamdownsmall -> INVERTED EXCLAMATION MARK */
	{ 0xf7a2, 0x00a2 }, /* centoldstyle -> CENT SIGN */
	{ 0xf7a8, 0x00a8 }, /* Dieresissmall -> DIAERESIS */
	{ 0xf7af, 0x00af }, /* Macronsmall -> MACRON */
	{ 0xf7b4, 0x00b4 }, /* Acutesmall -> ACUTE ACCENT */
	{ 0xf7b8, 0x00b8 }, /* Cedillasmall -> CEDILLA */
	{ 0xf7bf, 0x00bf }, /* questiondownsmall -> INVERTED QUESTION MARK */
	{ 0xf7e0, 0x00e0 }, /* Agravesmall -> LATIN SMALL LETTER A WITH GRAVE */
	{ 0xf7e1, 0x00e1 }, /* Aacutesmall -> LATIN SMALL LETTER A WITH ACUTE */
	{ 0xf7e2, 0x00e2 }, /* Acircumflexsmall -> LATIN SMALL LETTER A WITH CIRCUMFLEX */
	{ 0xf7e3, 0x00e3 }, /* Atildesmall -> LATIN SMALL LETTER A WITH TILDE */
	{ 0xf7e4, 0x00e4 }, /* Adieresissmall -> LATIN SMALL LETTER A WITH DIAERESIS */
	{ 0xf7e5, 0x00e5 }, /* Aringsmall -> LATIN SMALL LETTER A WITH RING ABOVE */
	{ 0xf7e6, 0x00e6 }, /* AEsmall -> LATIN SMALL LETTER AE */
	{ 0xf7e7, 0x00e7 }, /* Ccedillasmall -> LATIN SMALL LETTER C WITH CEDILLA */
	{ 0xf7e8, 0x00e8 }, /* Egravesmall -> LATIN SMALL LETTER E WITH GRAVE */
	{ 0xf7e9, 0x00e9 }, /* Eacutesmall -> LATIN SMALL LETTER E WITH ACUTE */
	{ 0xf7ea, 0x00ea }, /* Ecircumflexsmall -> LATIN SMALL LETTER E WITH CIRCUMFLEX */
	{ 0xf7eb, 0x00eb }, /* Edieresissmall -> LATIN SMALL LETTER E WITH DIAERESIS */
	{ 0xf7ec, 0x00ec }, /* Igravesmall -> LATIN SMALL LETTER I WITH GRAVE */
	{ 0xf7ed, 0x00ed }, /* Iacutesmall -> LATIN SMALL LETTER I WITH ACUTE */
	{ 0xf7ee, 0x00ee }, /* Icircumflexsmall -> LATIN SMALL LETTER I WITH CIRCUMFLEX */
	{ 0xf7ef, 0x00ef }, /* Idieresissmall -> LATIN SMALL LETTER I WITH DIAERESIS */
	{ 0xf7f0, 0x00f0 }, /* Ethsmall -> LATIN SMALL LETTER ETH */
	{ 0xf7f1, 0x00f1 }, /* Ntildesmall -> LATIN SMALL LETTER N WITH TILDE */
	{ 0xf7f2, 0x00f2 }, /* Ogravesmall -> LATIN SMALL LETTER O WITH GRAVE */
	{ 0xf7f3, 0x00f3 }, /* Oacutesmall -> LATIN SMALL LETTER O WITH ACUTE */
	{ 0xf7f4, 0x00f4 }, /* Ocircumflexsmall -> LATIN SMALL LETTER O WITH CIRCUMFLEX */
	{ 0xf7f5, 0x00f5 }, /* Otildesmall -> LATIN SMALL LETTER O WITH TILDE */
	{ 0xf7f6, 0x00f6 }, /* Odieresissmall -> LATIN SMALL LETTER O WITH DIAERESIS */
	{ 0xf7f8, 0x00f8 }, /* Oslashsmall -> LATIN SMALL LETTER O WITH STROKE */
	{ 0xf7f9, 0x00f9 }, /* Ugravesmall -> LATIN SMALL LETTER U WITH GRAVE */
	{ 0xf7fa, 0x00fa }, /* Uacutesmall -> LATIN SMALL LETTER U WITH ACUTE */
	{ 0xf7fb, 0x00fb }, /* Ucircumflexsmall -> LATIN SMALL LETTER U WITH CIRCUMFLEX */
	{ 0xf7fc, 0x00fc }, /* Udieresissmall -> LATIN SMALL LETTER U WITH DIAERESIS */
	{ 0xf7fd, 0x00fd }, /* Yacutesmall -> LATIN SMALL LETTER Y WITH ACUTE */
	{ 0xf7fe, 0x00fe }, /* Thornsmall -> LATIN SMALL LETTER THORN */
	{ 0xf7ff, 0x00ff }, /* Ydieresissmall -> LATIN SMALL LETTER Y WITH DIAERESIS */
	{ 0xf884, 0x0e31 }, /* maihanakatleftthai -> THAI CHARACTER MAI HAN-AKAT */
	{ 0xf885, 0x0e34 }, /* saraileftthai -> THAI CHARACTER SARA I */
	{ 0xf886, 0x0e35 }, /* saraiileftthai -> THAI CHARACTER SARA II */
	{ 0xf887, 0x0e36 }, /* saraueleftthai -> THAI CHARACTER SARA UE */
	{ 0xf888, 0x0e37 }, /* saraueeleftthai -> THAI CHARACTER SARA UEE */
	{ 0xf889, 0x0e47 }, /* maitaikhuleftthai -> THAI CHARACTER MAITAIKHU */
	{ 0xf88a, 0x0e48 }, /* maiekupperleftthai -> THAI CHARACTER MAI EK */
	{ 0xf88b, 0x0e48 }, /* maieklowrightthai -> THAI CHARACTER MAI EK */
	{ 0xf88c, 0x0e48 }, /* maieklowleftthai -> THAI CHARACTER MAI EK */
	{ 0xf88d, 0x0e49 }, /* maithoupperleftthai -> THAI CHARACTER MAI THO */
	{ 0xf88e, 0x0e49 }, /* maitholowrightthai -> THAI CHARACTER MAI THO */
	{ 0xf88f, 0x0e49 }, /* maitholowleftthai -> THAI CHARACTER MAI THO */
	{ 0xf890, 0x0e4a }, /* maitriupperleftthai -> THAI CHARACTER MAI TRI */
	{ 0xf891, 0x0e4a }, /* maitrilowrightthai -> THAI CHARACTER MAI TRI */
	{ 0xf892, 0x0e4a }, /* maitrilowleftthai -> THAI CHARACTER MAI TRI */
	{ 0xf893, 0x0e4b }, /* maichattawaupperleftthai -> THAI CHARACTER MAI CHATTAWA */
	{ 0xf894, 0x0e4b }, /* maichattawalowrightthai -> THAI CHARACTER MAI CHATTAWA */
	{ 0xf895, 0x0e4b }, /* maichattawalowleftthai -> THAI CHARACTER MAI CHATTAWA */
	{ 0xf896, 0x0e4c }, /* thanthakhatupperleftthai -> THAI CHARACTER THANTHAKHAT */
	{ 0xf897, 0x0e4c }, /* thanthakhatlowrightthai -> THAI CHARACTER THANTHAKHAT */
	{ 0xf898, 0x0e4c }, /* thanthakhatlowleftthai -> THAI CHARACTER THANTHAKHAT */
	{ 0xf899, 0x0e4d }, /* nikhahitleftthai -> THAI CHARACTER NIKHAHIT */
	{ 0xf8e5, 0x203e }, /* radicalex -> OVERLINE */
	{ 0xf8e6, 0x23d0 }, /* arrowvertex -> VERTICAL LINE EXTENSION */
	{ 0xf8e7, 0x23af }, /* arrowhorizex -> HORIZONTAL LINE EXTENSION */
	{ 0xf8e8, 0x00ae }, /* registersans -> REGISTERED SIGN */
	{ 0xf8e9, 0x00a9 }, /* copyrightsans -> COPYRIGHT SIGN */
	{ 0xf8ea, 0x2122 }, /* trademarksans -> TRADE MARK SIGN */
	{ 0xf8eb, 0x239b }, /* parenlefttp -> LEFT PARENTHESIS UPPER HOOK */
	{ 0xf8ec, 0x239c }, /* parenleftex -> LEFT PARENTHESIS EXTENSION */
	{ 0xf8ed, 0x239d }, /* parenleftbt -> LEFT PARENTHESIS LOWER HOOK */
	{ 0xf8ee, 0x23a1 }, /* bracketlefttp -> LEFT SQUARE BRACKET UPPER CORNER */
	{ 0xf8ef, 0x23a2 }, /* bracketleftex -> LEFT SQUARE BRACKET EXTENSION */
	{ 0xf8f0, 0x23a3 }, /* bracketleftbt -> LEFT SQUARE BRACKET LOWER CORNER */
	{ 0xf8f1, 0x23a7 }, /* bracelefttp -> LEFT CURLY BRACKET UPPER HOOK */
	{ 0xf8f2, 0x23a8 }, /* braceleftmid -> LEFT CURLY BRACKET MIDDLE PIECE */
	{ 0xf8f3, 0x23a9 }, /* braceleftbt -> LEFT CURLY BRACKET LOWER HOOK */
	{ 0xf8f4, 0x23aa }, /* braceex -> CURLY BRACKET EXTENSION */
	{ 0xf8f5, 0x23ae }, /* integralex -> INTEGRAL EXTENSION */
	{ 0xf8f6, 0x239e }, /* parenrighttp -> RIGHT PARENTHESIS UPPER HOOK */
	{ 0xf8f7, 0x239f }, /* parenrightex -> RIGHT PARENTHESIS EXTENSION */
	{ 0xf8f8, 0x23a0 }, /* parenrightbt -> RIGHT PARENTHESIS LOWER HOOK */
	{ 0xf8f9, 0x23a4 }, /* bracketrighttp -> RIGHT SQUARE BRACKET UPPER CORNER */
	{ 0xf8fa, 0x23a5 }, /* bracketrightex -> RIGHT SQUARE BRACKET EXTENSION */
	{ 0xf8fb, 0x23a6 }, /* bracketrightbt -> RIGHT SQUARE BRACKET LOWER CORNER */
	{ 0xf8fc, 0x23ab }, /* bracerighttp -> RIGHT CURLY BRACKET UPPER HOOK */
	{ 0xf8fd, 0x23ac }, /* bracerightmid -> RIGHT CURLY BRACKET MIDDLE PIECE */
	{ 0xf8fe, 0x23ad }, /* bracerightbt -> RIGHT CURLY BRACKET LOWER HOOK */
};
