"""Stage 5: emit the C table from review decisions.

usage: emit_table.py review.json out.h [candidates.jsonl ...]
Candidate files are optional: every decision records its label ("proposed" for
accepts, "label" for relabels).

review.json: { "<hash>": {"decision": "accept" | "reject" | "relabel", "label": "<char>", "note": "..."} }
Entries included: decision accept (proposed label) or relabel (reviewed label).
Output: a C header with a sorted array for binary search, keyed by outline hash v1.
"""
import json, sys, unicodedata
CANONICAL = {'\u00b5': '\u03bc'}
LIGATURES = {'ff': '\ufb00', 'fi': '\ufb01', 'fl': '\ufb02', 'ffi': '\ufb03', 'ffl': '\ufb04', 'st': '\ufb06'}
SEQUENCE = 0x110000   # FZ_KNOWN_OUTLINE_SEQUENCE
sequences = []
review = json.load(open(sys.argv[1])); out = sys.argv[2]
cands = {}
for path in sys.argv[3:]:
    for l in open(path):
        r = json.loads(l); cands[r['h']] = r
entries = []
for h, rv in review.items():
    if rv['decision'] == 'accept': lab = rv.get('proposed') or cands[h]['label']
    elif rv['decision'] == 'relabel': lab = rv['label']
    else: continue
    # Canonical code points: MICRO SIGN is emitted as GREEK SMALL LETTER MU (NFKC-equal),
    # so every mu entry is Greek and the C override rules treat them alike.
    lab = CANONICAL.get(lab, lab)
    # Ligatures with a code point of their own are stored as it (MuPDF expands
    # them unless ligatures are preserved); any other multi-letter label is a sequence.
    lab = LIGATURES.get(lab, lab)
    if len(lab) == 1:
        entries.append((int(h, 16), ord(lab)))
    else:
        assert lab.isalpha() and len(lab) <= 4, (h, lab)
        if lab not in sequences: sequences.append(lab)
        entries.append((int(h, 16), SEQUENCE + sequences.index(lab)))
entries.sort()
with open(out, 'w') as w:
    w.write('/* Generated by emit_table.py from a reviewed corpus scan. Do not edit.\n')
    w.write(' * Maps glyph outline hash v1 (see known-glyph-outlines.c) to the character\n')
    w.write(' * the outline draws. Sorted by hash for binary search. */\n\n')
    w.write('/* Values FZ_KNOWN_OUTLINE_SEQUENCE + n: ligatures without a code point. */\n')
    w.write('static const char *const fz_known_glyph_outline_sequences[] =\n{\n')
    for q in sequences:
        w.write(f'\t"{q}",\n')
    w.write('\tNULL\n};\n\n')
    w.write('static const known_glyph_outline fz_known_glyph_outlines[] =\n{\n')
    for h, u in entries:
        if u >= SEQUENCE:
            q = sequences[u - SEQUENCE]
            w.write(f'\t{{ 0x{h:016x}ULL, 0x{u:06x} }}, /* "{q}" */\n')
        else:
            w.write(f'\t{{ 0x{h:016x}ULL, 0x{u:04x} }}, /* U+{u:04X} {unicodedata.name(chr(u), "")} */\n')
    w.write('};\n')
print('entries', len(entries), 'sequences', len(sequences))
