"""Emit source/fitz/symbol-encoding-table.h: the Adobe Symbol encoding as Unicode.

usage: emit_symbol_encoding.py <mupdf root> <out.h>
(needs pypdf, fonttools, freetype-py)

Source: pypdf's copy of Adobe's symbol.txt. Only codes that MuPDF's bundled
URW Standard Symbols font defines are kept (pypdf fills undefined codes with
their Latin-1 values), and each value is cross-checked against the Adobe Glyph
List name of the URW glyph. Adobe private-use values get the standard Unicode
character (Apple's SYMBOL.TXT does the same).
"""
import sys, unicodedata, freetype
from fontTools.agl import toUnicode
import pypdf._codecs.symbol as symbol

root, out = sys.argv[1], sys.argv[2]
FIX = {
    0xF6D9: 0xA9, 0xF6DA: 0xAE, 0xF6DB: 0x2122,     # copyright/registered/trademark serif
    0xF8E8: 0xAE, 0xF8E9: 0xA9, 0xF8EA: 0x2122,     # ... sans
    0xF8E5: 0x203E, 0xF8E6: 0x23D0, 0xF8E7: 0x23AF,  # radical, vertical and horizontal arrow extenders
    0xF8EB: 0x239B, 0xF8EC: 0x239C, 0xF8ED: 0x239D, 0xF8EE: 0x23A1, 0xF8EF: 0x23A2, 0xF8F0: 0x23A3,
    0xF8F1: 0x23A7, 0xF8F2: 0x23A8, 0xF8F3: 0x23A9, 0xF8F4: 0x23AA, 0xF8F5: 0x23AE,
    0xF8F6: 0x239E, 0xF8F7: 0x239F, 0xF8F8: 0x23A0, 0xF8F9: 0x23A4, 0xF8FA: 0x23A5, 0xF8FB: 0x23A6,
    0xF8FC: 0x23AB, 0xF8FD: 0x23AC, 0xF8FE: 0x23AD,
}
# Where pypdf and the Adobe Glyph List disagree, the glyph list wins.
AGL_WINS = {0xA4}   # fraction: U+2044 FRACTION SLASH, not U+2215 DIVISION SLASH

face = freetype.Face(f'{root}/resources/fonts/urw/StandardSymbolsPS.cff')
face.select_charmap(freetype.FT_ENCODING_ADOBE_CUSTOM)
table = {}
for code in range(0x20, 0x100):
    gid = face.get_char_index(code)
    if not gid:
        continue
    name = face.get_glyph_name(gid).decode()
    agl = toUnicode(name)
    u = 0x20 if code == 0x20 else ord(symbol._symbol_encoding[code])
    u = FIX.get(u, u)
    if code in AGL_WINS:
        u = ord(agl)
    if u < 0x20 or 0x7F <= u < 0xA0 or 0xE000 <= u <= 0xF8FF:
        continue
    if agl and len(agl) == 1 and not 0xE000 <= ord(agl) <= 0xF8FF and ord(agl) != u:
        # mu: the glyph list says MICRO SIGN; the Greek letter is kept, as in the outline table
        assert (name, u) == ('mu', 0x3BC), (hex(code), name, agl, hex(u))
    table[code] = u

with open(out, 'w') as w:
    w.write('/* Adobe Symbol encoding for character codes 0x20-0xFF, indexed by code - 0x20;\n'
            ' * 0 = undefined. Adobe private-use values (serif/sans copyright, registered\n'
            ' * and trademark, extensible bracket and arrow pieces) are given their standard\n'
            ' * Unicode characters. Generated by emit_symbol_encoding.py. Do not edit. */\n\n')
    w.write('static const unsigned short fz_symbol_encoding_unicode[224] =\n{\n')
    for code in range(0x20, 0x100):
        u = table.get(code, 0)
        w.write(f'\t0x{u:04x}, /* 0x{code:02X} {unicodedata.name(chr(u), "") if u else "undefined"} */\n')
    w.write('};\n')
print('codes', len(table))
