"""Emit source/fitz/adobe-private-use-table.h: Adobe Corporate Use values -> Unicode.

usage: emit_adobe_private_use.py <mupdf root> <out.h>

The Adobe Glyph List (source/fitz/glyphlist.h) gives some glyph names a
value in Adobe's Corporate Use Subarea (U+F6BE-U+F8FF): small capitals
("Asmall"), oldstyle and fitted figures ("oneoldstyle", "onefitted"),
superiors and inferiors, serif/sans copyright signs, extensible bracket
pieces and Thai left-shifted marks. Each gets the character it is a variant
of: small capitals the lowercase letter, figures the digit, superiors the
base letter, pieces the Unicode bracket pieces. Values with no such
character (Cyrillic "afii" forms, "LL", "rupiah", "apple", ...) are left out.
"""
import re, sys, unicodedata

root, out = sys.argv[1], sys.argv[2]
src = open(f'{root}/source/fitz/glyphlist.h').read()


def block(name):
    return re.search(r'%s\[\] = \{(.*?)\};' % name, src, re.S).group(1)


names = re.findall(r'"([^"]*)"', block('single_name_list'))
codes = [int(x, 0) for x in re.findall(r'0x[0-9a-fA-F]+|\b\d+\b', block('single_code_list'))]
agl = dict(zip(names, codes))
pua = {c: n for n, c in agl.items() if 0xF6BE <= c <= 0xF8FF}

PIECES = {'radicalex': 0x203E, 'arrowvertex': 0x23D0, 'arrowhorizex': 0x23AF,
          'parenlefttp': 0x239B, 'parenleftex': 0x239C, 'parenleftbt': 0x239D,
          'bracketlefttp': 0x23A1, 'bracketleftex': 0x23A2, 'bracketleftbt': 0x23A3,
          'bracelefttp': 0x23A7, 'braceleftmid': 0x23A8, 'braceleftbt': 0x23A9, 'braceex': 0x23AA,
          'integralex': 0x23AE, 'parenrighttp': 0x239E, 'parenrightex': 0x239F, 'parenrightbt': 0x23A0,
          'bracketrighttp': 0x23A4, 'bracketrightex': 0x23A5, 'bracketrightbt': 0x23A6,
          'bracerighttp': 0x23AB, 'bracerightmid': 0x23AC, 'bracerightbt': 0x23AD}
SIGNS = {'copyrightserif': 0xA9, 'copyrightsans': 0xA9, 'registerserif': 0xAE, 'registersans': 0xAE,
         'trademarkserif': 0x2122, 'trademarksans': 0x2122, 'onefitted': 0x31, 'dotlessj': 0x237}
THAI = {'maihanakat': 0xE31, 'sarai': 0xE34, 'saraii': 0xE35, 'saraue': 0xE36, 'sarauee': 0xE37,
        'maitaikhu': 0xE47, 'maiek': 0xE48, 'maitho': 0xE49, 'maitri': 0xE4A, 'maichattawa': 0xE4B,
        'thanthakhat': 0xE4C, 'nikhahit': 0xE4D}


def plain(name):
    """Unicode value of an AGL name outside the private-use area, or None."""
    u = agl.get(name)
    return u if u is not None and not 0xE000 <= u <= 0xF8FF else None


def fold(name):
    if name in PIECES: return PIECES[name]
    if name in SIGNS: return SIGNS[name]
    m = re.match(r'(\w+?)(upperleft|lowright|lowleft|left)thai$', name)
    if m: return THAI.get(m.group(1))
    for suffix in ('small', 'oldstyle', 'superior', 'inferior'):
        if name.endswith(suffix) and len(name) > len(suffix):
            base = name[:-len(suffix)]
            u = plain(base)
            if u is not None and suffix == 'small' and chr(u).isalpha():
                return ord(chr(u).lower()) if len(chr(u).lower()) == 1 else u
            if u is None:
                u = plain(base.lower())   # "Brevesmall" -> breve, "Acutesmall" -> acute
            return u
    # capital spacing accents ("Acute", "Caron"): the ordinary accent
    return plain(name.lower()) if name[:1].isupper() else None


table = {}
for c, n in sorted(pua.items()):
    u = fold(n)
    if u is None or u < 0x20 or 0xE000 <= u <= 0xF8FF:
        continue
    table[c] = u
with open(out, 'w') as w:
    w.write('/* Adobe Corporate Use values of Adobe Glyph List names, mapped to the\n'
            ' * character each is a variant of. Sorted by value for binary search.\n'
            ' * Generated by emit_adobe_private_use.py. Do not edit. */\n\n')
    w.write('static const struct { unsigned short pua, ucs; } fz_adobe_private_use[] =\n{\n')
    for c, u in sorted(table.items()):
        w.write(f'\t{{ 0x{c:04x}, 0x{u:04x} }}, /* {pua[c]} -> {unicodedata.name(chr(u), "")} */\n')
    w.write('};\n')
print('entries', len(table), 'of', len(pua))
skipped = sorted(n for c, n in pua.items() if c not in table)
print('skipped', skipped)
